<a href="https://colab.research.google.com/github/adamazanos/handling_null_values/blob/main/handling_null_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Cara Menghandling Null/NaN value dalam data set


Projek ini bertujuan untuk mengecek cara mengisi dan menghendle null values dalam data set. 

dalam kasus Data kasus ini menggunakan data bps "kemungkinan terkena tindak pidana (per 100rb pernduduk)"

data set yang di gunakan adalah

---

Risiko Penduduk Terkena Tindak Pidana Per 100k Penduduk

SINGKATAN  = RPTTP100K 

DITARIK MENGGUNAKAN TABEL DINAMIS

LINK = https://www.bps.go.id/indicator/34/299/1/risiko-penduduk-terkena-tindak-pidana-per-100-000-penduduk-.html

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data Risiko Penduduk Terkena Tindak Pidana Per 100k Penduduk

In [2]:
#data_rpttp100k  = pd.read_excel('/content/RPTTP100K .xlsx')
data_rpttp100k  = pd.read_csv('https://raw.githubusercontent.com/adamazanos/korelasi_ipm_rpttp100k/main/Risiko%20Penduduk%20Terkena%20Tindak%20Pidana%20(Per%20100.000%20Penduduk)/EDITED%20RPTTP100K/RPTTP100K%20.csv' , sep=';')
data_rpttp100k

,Kepolisian Daerah,RPTTP100K 2021,RPTTP100K 2020,RPTTP100K 2019,RPTTP100K 2018,RPTTP100K 2017,RPTTP100K 2016,RPTTP100K 2015,RPTTP100K 2014,RPTTP100K 2013,RPTTP100K 2012,RPTTP100K 2011,RPTTP100K 2010
0,ACEH,125.0,149.0,144.0,169.0,171.0,193.0,164.0,158.0,181.0,224.0,222.0,225.0
1,SUMATERA UTARA,250.0,231.0,216.0,231.0,280.0,266.0,256.0,268.0,308.0,252.0,285.0,251.0
2,SUMATERA BARAT,103.0,150.0,208.0,243.0,248.0,287.0,317.0,298.0,289.0,297.0,258.0,239.0
3,RIAU,110.0,123.0,99.0,109.0,103.0,134.0,155.0,157.0,159.0,195.0,130.0,158.0
4,JAMBI,104.0,134.0,195.0,180.0,271.0,277.0,316.0,230.0,201.0,209.0,153.0,123.0
5,SUMATERA SELATAN,153.0,147.0,156.0,164.0,190.0,253.0,259.0,290.0,297.0,294.0,265.0,250.0
6,BENGKULU,177.0,172.0,179.0,175.0,252.0,315.0,242.0,215.0,258.0,221.0,196.0,152.0
7,LAMPUNG,115.0,92.0,103.0,108.0,134.0,129.0,115.0,99.0,62.0,56.0,77.0,61.0
8,KEP. BANGKA BELITUNG,108.0,133.0,136.0,143.0,135.0,153.0,140.0,134.0,194.0,497.0,262.0,253.0
9,KEP. RIAU,111.0,127.0,152.0,164.0,176.0,248.0,255.0,240.0,232.0,347.0,348.0,396.0
10,METRO JAYA,277.0,105.0,127.0,137.0,138.0,174.0,181.0,186.0,213.0,256.0,260.0,297.0
11,JAWA BARAT,15.0,29.0,34.0,42.0,65.0,76.0,73.0,71.0,66.0,74.0,80.0,46.0
12,JAWA TENGAH,26.0,31.0,30.0,27.0,35.0,42.0,48.0,49.0,46.0,34.0,47.0,148.0
13,DI YOGYAKARTA,123.0,200.0,177.0,179.0,193.0,227.0,266.0,201.0,191.0,261.0,184.0,512.0
14,JAWA TIMUR,48.0,44.0,69.0,67.0,88.0,74.0,92.0,37.0,45.0,63.0,78.0,47.0
15,BANTEN,27.0,63.0,49.0,54.0,55.0,92.0,101.0,115.0,87.0,76.0,64.0,77.0
16,BALI,55.0,60.0,72.0,76.0,85.0,115.0,123.0,123.0,148.0,144.0,153.0,156.0
17,NUSA TENGGARA BARAT,122.0,167.0,165.0,130.0,164.0,161.0,126.0,156.0,195.0,223.0,204.0,232.0
18,NUSA TENGGARA TIMUR,90.0,88.0,111.0,118.0,127.0,153.0,133.0,131.0,141.0,145.0,120.0,81.0
19,KALIMANTAN BARAT,80.0,76.0,96.0,118.0,122.0,153.0,141.0,179.0,212.0,216.0,216.0,180.0
20,KALIMANTAN TENGAH,91.0,62.0,94.0,102.0,104.0,149.0,110.0,124.0,131.0,132.0,233.0,112.0
21,KALIMANTAN SELATAN,118.0,196.0,130.0,138.0,160.0,181.0,174.0,156.0,188.0,96.0,14.0,55.0
22,KALIMANTAN TIMUR,126.0,100.0,124.0,176.0,214.0,219.0,221.0,230.0,285.0,302.0,296.0,314.0
23,KALIMANTAN UTARA,140.0,146.0,127.0,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,SULAWESI UTARA,249.0,252.0,302.0,416.0,324.0,411.0,328.0,263.0,224.0,299.0,496.0,382.0
25,SULAWESI TENGAH,169.0,179.0,211.0,316.0,345.0,334.0,317.0,281.0,286.0,308.0,265.0,493.0
26,SULAWESI SELATAN,166.0,145.0,190.0,255.0,256.0,154.0,166.0,157.0,182.0,204.0,252.0,177.0
27,SULAWESI TENGGARA,91.0,81.0,47.0,49.0,110.0,150.0,149.0,224.0,304.0,303.0,265.0,262.0
28,GORONTALO,208.0,214.0,203.0,243.0,265.0,332.0,302.0,305.0,344.0,271.0,287.0,340.0
29,SULAWESI BARAT,110.0,125.0,148.0,144.0,146.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,MALUKU,177.0,303.0,200.0,158.0,177.0,152.0,111.0,144.0,135.0,126.0,110.0,292.0
31,MALUKU UTARA,82.0,69.0,59.0,60.0,65.0,94.0,71.0,101.0,108.0,96.0,91.0,198.0
32,PAPUA BARAT,289.0,328.0,325.0,380.0,146.0,257.0,160.0,NaN,NaN,NaN,NaN,NaN
33,PAPUA,186.0,208.0,214.0,224.0,208.0,358.0,233.0,214.0,219.0,263.0,250.0,181.0
34,INDONESIA,90.0,94.0,103.0,113.0,129.0,140.0,140.0,131.0,140.0,146.0,149.0,142.0

In [3]:
print(data_rpttp100k.isnull().sum())

Kepolisian Daerah    0
RPTTP100K 2021       0
RPTTP100K 2020       0
RPTTP100K 2019       0
RPTTP100K 2018       0
RPTTP100K 2017       1
RPTTP100K 2016       2
RPTTP100K 2015       2
RPTTP100K 2014       3
RPTTP100K 2013       3
RPTTP100K 2012       3
RPTTP100K 2011       3
RPTTP100K 2010       3
dtype: int64

In [4]:
list(data_rpttp100k.columns.values)

['Kepolisian Daerah',
 'RPTTP100K 2021',
 'RPTTP100K 2020',
 'RPTTP100K 2019',
 'RPTTP100K 2018',
 'RPTTP100K 2017',
 'RPTTP100K 2016',
 'RPTTP100K 2015',
 'RPTTP100K 2014',
 'RPTTP100K 2013',
 'RPTTP100K 2012',
 'RPTTP100K 2011',
 'RPTTP100K 2010']

#Cleaning Data Mentah

In [20]:
data_rpttp100k

,Kepolisian Daerah,RPTTP100K 2021,RPTTP100K 2020,RPTTP100K 2019,RPTTP100K 2018,RPTTP100K 2017,RPTTP100K 2016,RPTTP100K 2015,RPTTP100K 2014,RPTTP100K 2013,RPTTP100K 2012,RPTTP100K 2011,RPTTP100K 2010
0,ACEH,125.0,149.0,144.0,169.0,171.0,193.0,164.0,158.0,181.0,224.0,222.0,225.0
1,SUMATERA UTARA,250.0,231.0,216.0,231.0,280.0,266.0,256.0,268.0,308.0,252.0,285.0,251.0
2,SUMATERA BARAT,103.0,150.0,208.0,243.0,248.0,287.0,317.0,298.0,289.0,297.0,258.0,239.0
3,RIAU,110.0,123.0,99.0,109.0,103.0,134.0,155.0,157.0,159.0,195.0,130.0,158.0
4,JAMBI,104.0,134.0,195.0,180.0,271.0,277.0,316.0,230.0,201.0,209.0,153.0,123.0
5,SUMATERA SELATAN,153.0,147.0,156.0,164.0,190.0,253.0,259.0,290.0,297.0,294.0,265.0,250.0
6,BENGKULU,177.0,172.0,179.0,175.0,252.0,315.0,242.0,215.0,258.0,221.0,196.0,152.0
7,LAMPUNG,115.0,92.0,103.0,108.0,134.0,129.0,115.0,99.0,62.0,56.0,77.0,61.0
8,KEP. BANGKA BELITUNG,108.0,133.0,136.0,143.0,135.0,153.0,140.0,134.0,194.0,497.0,262.0,253.0
9,KEP. RIAU,111.0,127.0,152.0,164.0,176.0,248.0,255.0,240.0,232.0,347.0,348.0,396.0
10,METRO JAYA,277.0,105.0,127.0,137.0,138.0,174.0,181.0,186.0,213.0,256.0,260.0,297.0
11,JAWA BARAT,15.0,29.0,34.0,42.0,65.0,76.0,73.0,71.0,66.0,74.0,80.0,46.0
12,JAWA TENGAH,26.0,31.0,30.0,27.0,35.0,42.0,48.0,49.0,46.0,34.0,47.0,148.0
13,DI YOGYAKARTA,123.0,200.0,177.0,179.0,193.0,227.0,266.0,201.0,191.0,261.0,184.0,512.0
14,JAWA TIMUR,48.0,44.0,69.0,67.0,88.0,74.0,92.0,37.0,45.0,63.0,78.0,47.0
15,BANTEN,27.0,63.0,49.0,54.0,55.0,92.0,101.0,115.0,87.0,76.0,64.0,77.0
16,BALI,55.0,60.0,72.0,76.0,85.0,115.0,123.0,123.0,148.0,144.0,153.0,156.0
17,NUSA TENGGARA BARAT,122.0,167.0,165.0,130.0,164.0,161.0,126.0,156.0,195.0,223.0,204.0,232.0
18,NUSA TENGGARA TIMUR,90.0,88.0,111.0,118.0,127.0,153.0,133.0,131.0,141.0,145.0,120.0,81.0
19,KALIMANTAN BARAT,80.0,76.0,96.0,118.0,122.0,153.0,141.0,179.0,212.0,216.0,216.0,180.0
20,KALIMANTAN TENGAH,91.0,62.0,94.0,102.0,104.0,149.0,110.0,124.0,131.0,132.0,233.0,112.0
21,KALIMANTAN SELATAN,118.0,196.0,130.0,138.0,160.0,181.0,174.0,156.0,188.0,96.0,14.0,55.0
22,KALIMANTAN TIMUR,126.0,100.0,124.0,176.0,214.0,219.0,221.0,230.0,285.0,302.0,296.0,314.0
23,KALIMANTAN UTARA,140.0,146.0,127.0,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,SULAWESI UTARA,249.0,252.0,302.0,416.0,324.0,411.0,328.0,263.0,224.0,299.0,496.0,382.0
25,SULAWESI TENGAH,169.0,179.0,211.0,316.0,345.0,334.0,317.0,281.0,286.0,308.0,265.0,493.0
26,SULAWESI SELATAN,166.0,145.0,190.0,255.0,256.0,154.0,166.0,157.0,182.0,204.0,252.0,177.0
27,SULAWESI TENGGARA,91.0,81.0,47.0,49.0,110.0,150.0,149.0,224.0,304.0,303.0,265.0,262.0
28,GORONTALO,208.0,214.0,203.0,243.0,265.0,332.0,302.0,305.0,344.0,271.0,287.0,340.0
29,SULAWESI BARAT,110.0,125.0,148.0,144.0,146.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,MALUKU,177.0,303.0,200.0,158.0,177.0,152.0,111.0,144.0,135.0,126.0,110.0,292.0
31,MALUKU UTARA,82.0,69.0,59.0,60.0,65.0,94.0,71.0,101.0,108.0,96.0,91.0,198.0
32,PAPUA BARAT,289.0,328.0,325.0,380.0,146.0,257.0,160.0,NaN,NaN,NaN,NaN,NaN
33,PAPUA,186.0,208.0,214.0,224.0,208.0,358.0,233.0,214.0,219.0,263.0,250.0,181.0
34,INDONESIA,90.0,94.0,103.0,113.0,129.0,140.0,140.0,131.0,140.0,146.0,149.0,142.0

Ditemukan ada data kosong di data set RPTTP100K pada provinsi

1.   KALIMANTAN UTARA tahun 2017 - 2010 RPTTP100K 

2.   SULAWESI BARAT tahun 2016 - 2010 RPTTP100K 

3.   PAPUA BARAT tahun 2014 - 2010 RPTTP100K

Untuk handlingnya ada 2 cara

1.   KALIMANTAN UTARA tahun 2017 - 2010 RPTTP100K 

Di drop karena provinsi tidak berdiri

dan

2.   SULAWESI BARAT tahun 2016 - 2010 RPTTP100K 

3.   PAPUA BARAT tahun 2014 - 2010 RPTTP100K

Null value bisa di isi antara menggunakan mean atau modus

In [21]:
df = data_rpttp100k.drop(23)

In [22]:
df

,Kepolisian Daerah,RPTTP100K 2021,RPTTP100K 2020,RPTTP100K 2019,RPTTP100K 2018,RPTTP100K 2017,RPTTP100K 2016,RPTTP100K 2015,RPTTP100K 2014,RPTTP100K 2013,RPTTP100K 2012,RPTTP100K 2011,RPTTP100K 2010
0,ACEH,125.0,149.0,144.0,169.0,171.0,193.0,164.0,158.0,181.0,224.0,222.0,225.0
1,SUMATERA UTARA,250.0,231.0,216.0,231.0,280.0,266.0,256.0,268.0,308.0,252.0,285.0,251.0
2,SUMATERA BARAT,103.0,150.0,208.0,243.0,248.0,287.0,317.0,298.0,289.0,297.0,258.0,239.0
3,RIAU,110.0,123.0,99.0,109.0,103.0,134.0,155.0,157.0,159.0,195.0,130.0,158.0
4,JAMBI,104.0,134.0,195.0,180.0,271.0,277.0,316.0,230.0,201.0,209.0,153.0,123.0
5,SUMATERA SELATAN,153.0,147.0,156.0,164.0,190.0,253.0,259.0,290.0,297.0,294.0,265.0,250.0
6,BENGKULU,177.0,172.0,179.0,175.0,252.0,315.0,242.0,215.0,258.0,221.0,196.0,152.0
7,LAMPUNG,115.0,92.0,103.0,108.0,134.0,129.0,115.0,99.0,62.0,56.0,77.0,61.0
8,KEP. BANGKA BELITUNG,108.0,133.0,136.0,143.0,135.0,153.0,140.0,134.0,194.0,497.0,262.0,253.0
9,KEP. RIAU,111.0,127.0,152.0,164.0,176.0,248.0,255.0,240.0,232.0,347.0,348.0,396.0
10,METRO JAYA,277.0,105.0,127.0,137.0,138.0,174.0,181.0,186.0,213.0,256.0,260.0,297.0
11,JAWA BARAT,15.0,29.0,34.0,42.0,65.0,76.0,73.0,71.0,66.0,74.0,80.0,46.0
12,JAWA TENGAH,26.0,31.0,30.0,27.0,35.0,42.0,48.0,49.0,46.0,34.0,47.0,148.0
13,DI YOGYAKARTA,123.0,200.0,177.0,179.0,193.0,227.0,266.0,201.0,191.0,261.0,184.0,512.0
14,JAWA TIMUR,48.0,44.0,69.0,67.0,88.0,74.0,92.0,37.0,45.0,63.0,78.0,47.0
15,BANTEN,27.0,63.0,49.0,54.0,55.0,92.0,101.0,115.0,87.0,76.0,64.0,77.0
16,BALI,55.0,60.0,72.0,76.0,85.0,115.0,123.0,123.0,148.0,144.0,153.0,156.0
17,NUSA TENGGARA BARAT,122.0,167.0,165.0,130.0,164.0,161.0,126.0,156.0,195.0,223.0,204.0,232.0
18,NUSA TENGGARA TIMUR,90.0,88.0,111.0,118.0,127.0,153.0,133.0,131.0,141.0,145.0,120.0,81.0
19,KALIMANTAN BARAT,80.0,76.0,96.0,118.0,122.0,153.0,141.0,179.0,212.0,216.0,216.0,180.0
20,KALIMANTAN TENGAH,91.0,62.0,94.0,102.0,104.0,149.0,110.0,124.0,131.0,132.0,233.0,112.0
21,KALIMANTAN SELATAN,118.0,196.0,130.0,138.0,160.0,181.0,174.0,156.0,188.0,96.0,14.0,55.0
22,KALIMANTAN TIMUR,126.0,100.0,124.0,176.0,214.0,219.0,221.0,230.0,285.0,302.0,296.0,314.0
24,SULAWESI UTARA,249.0,252.0,302.0,416.0,324.0,411.0,328.0,263.0,224.0,299.0,496.0,382.0
25,SULAWESI TENGAH,169.0,179.0,211.0,316.0,345.0,334.0,317.0,281.0,286.0,308.0,265.0,493.0
26,SULAWESI SELATAN,166.0,145.0,190.0,255.0,256.0,154.0,166.0,157.0,182.0,204.0,252.0,177.0
27,SULAWESI TENGGARA,91.0,81.0,47.0,49.0,110.0,150.0,149.0,224.0,304.0,303.0,265.0,262.0
28,GORONTALO,208.0,214.0,203.0,243.0,265.0,332.0,302.0,305.0,344.0,271.0,287.0,340.0
29,SULAWESI BARAT,110.0,125.0,148.0,144.0,146.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,MALUKU,177.0,303.0,200.0,158.0,177.0,152.0,111.0,144.0,135.0,126.0,110.0,292.0
31,MALUKU UTARA,82.0,69.0,59.0,60.0,65.0,94.0,71.0,101.0,108.0,96.0,91.0,198.0
32,PAPUA BARAT,289.0,328.0,325.0,380.0,146.0,257.0,160.0,NaN,NaN,NaN,NaN,NaN
33,PAPUA,186.0,208.0,214.0,224.0,208.0,358.0,233.0,214.0,219.0,263.0,250.0,181.0
34,INDONESIA,90.0,94.0,103.0,113.0,129.0,140.0,140.0,131.0,140.0,146.0,149.0,142.0

In [23]:
df_nan  = df.drop(columns='Kepolisian Daerah')

In [24]:
df_nan

,RPTTP100K 2021,RPTTP100K 2020,RPTTP100K 2019,RPTTP100K 2018,RPTTP100K 2017,RPTTP100K 2016,RPTTP100K 2015,RPTTP100K 2014,RPTTP100K 2013,RPTTP100K 2012,RPTTP100K 2011,RPTTP100K 2010
0,125.0,149.0,144.0,169.0,171.0,193.0,164.0,158.0,181.0,224.0,222.0,225.0
1,250.0,231.0,216.0,231.0,280.0,266.0,256.0,268.0,308.0,252.0,285.0,251.0
2,103.0,150.0,208.0,243.0,248.0,287.0,317.0,298.0,289.0,297.0,258.0,239.0
3,110.0,123.0,99.0,109.0,103.0,134.0,155.0,157.0,159.0,195.0,130.0,158.0
4,104.0,134.0,195.0,180.0,271.0,277.0,316.0,230.0,201.0,209.0,153.0,123.0
5,153.0,147.0,156.0,164.0,190.0,253.0,259.0,290.0,297.0,294.0,265.0,250.0
6,177.0,172.0,179.0,175.0,252.0,315.0,242.0,215.0,258.0,221.0,196.0,152.0
7,115.0,92.0,103.0,108.0,134.0,129.0,115.0,99.0,62.0,56.0,77.0,61.0
8,108.0,133.0,136.0,143.0,135.0,153.0,140.0,134.0,194.0,497.0,262.0,253.0
9,111.0,127.0,152.0,164.0,176.0,248.0,255.0,240.0,232.0,347.0,348.0,396.0
10,277.0,105.0,127.0,137.0,138.0,174.0,181.0,186.0,213.0,256.0,260.0,297.0
11,15.0,29.0,34.0,42.0,65.0,76.0,73.0,71.0,66.0,74.0,80.0,46.0
12,26.0,31.0,30.0,27.0,35.0,42.0,48.0,49.0,46.0,34.0,47.0,148.0
13,123.0,200.0,177.0,179.0,193.0,227.0,266.0,201.0,191.0,261.0,184.0,512.0
14,48.0,44.0,69.0,67.0,88.0,74.0,92.0,37.0,45.0,63.0,78.0,47.0
15,27.0,63.0,49.0,54.0,55.0,92.0,101.0,115.0,87.0,76.0,64.0,77.0
16,55.0,60.0,72.0,76.0,85.0,115.0,123.0,123.0,148.0,144.0,153.0,156.0
17,122.0,167.0,165.0,130.0,164.0,161.0,126.0,156.0,195.0,223.0,204.0,232.0
18,90.0,88.0,111.0,118.0,127.0,153.0,133.0,131.0,141.0,145.0,120.0,81.0
19,80.0,76.0,96.0,118.0,122.0,153.0,141.0,179.0,212.0,216.0,216.0,180.0
20,91.0,62.0,94.0,102.0,104.0,149.0,110.0,124.0,131.0,132.0,233.0,112.0
21,118.0,196.0,130.0,138.0,160.0,181.0,174.0,156.0,188.0,96.0,14.0,55.0
22,126.0,100.0,124.0,176.0,214.0,219.0,221.0,230.0,285.0,302.0,296.0,314.0
24,249.0,252.0,302.0,416.0,324.0,411.0,328.0,263.0,224.0,299.0,496.0,382.0
25,169.0,179.0,211.0,316.0,345.0,334.0,317.0,281.0,286.0,308.0,265.0,493.0
26,166.0,145.0,190.0,255.0,256.0,154.0,166.0,157.0,182.0,204.0,252.0,177.0
27,91.0,81.0,47.0,49.0,110.0,150.0,149.0,224.0,304.0,303.0,265.0,262.0
28,208.0,214.0,203.0,243.0,265.0,332.0,302.0,305.0,344.0,271.0,287.0,340.0
29,110.0,125.0,148.0,144.0,146.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,177.0,303.0,200.0,158.0,177.0,152.0,111.0,144.0,135.0,126.0,110.0,292.0
31,82.0,69.0,59.0,60.0,65.0,94.0,71.0,101.0,108.0,96.0,91.0,198.0
32,289.0,328.0,325.0,380.0,146.0,257.0,160.0,NaN,NaN,NaN,NaN,NaN
33,186.0,208.0,214.0,224.0,208.0,358.0,233.0,214.0,219.0,263.0,250.0,181.0
34,90.0,94.0,103.0,113.0,129.0,140.0,140.0,131.0,140.0,146.0,149.0,142.0

#Imputasi iterative

Menggunakan guide https://www.youtube.com/watch?v=W3A7WAeS31Y

In [25]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression

In [26]:
linearreg = LinearRegression()
imp = IterativeImputer(estimator=linearreg,missing_values=np.nan, max_iter=5, verbose=2,imputation_order='roman',random_state=0)
ImputedData = imp.fit_transform(df_nan)

[IterativeImputer] Completing matrix with shape (34, 12)
[IterativeImputer] Ending imputation round 1/5, elapsed time 0.01
[IterativeImputer] Change: 475.5444148881143, scaled tolerance: 0.512
[IterativeImputer] Ending imputation round 2/5, elapsed time 0.03
[IterativeImputer] Change: 244.17215822174302, scaled tolerance: 0.512
[IterativeImputer] Ending imputation round 3/5, elapsed time 0.04
[IterativeImputer] Change: 130.3291298664005, scaled tolerance: 0.512
[IterativeImputer] Ending imputation round 4/5, elapsed time 0.05
[IterativeImputer] Change: 57.989363349838605, scaled tolerance: 0.512
[IterativeImputer] Ending imputation round 5/5, elapsed time 0.06
[IterativeImputer] Change: 24.93549628044842, scaled tolerance: 0.512

/usr/local/lib/python3.8/dist-packages/sklearn/impute/_iterative.py:699: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [27]:
pd.DataFrame(ImputedData)

,0,1,2,3,4,5,6,7,8,9,10,11
0,125.0,149.0,144.0,169.0,171.0,193.000000,164.000000,158.000000,181.000000,224.000000,222.000000,225.000000
1,250.0,231.0,216.0,231.0,280.0,266.000000,256.000000,268.000000,308.000000,252.000000,285.000000,251.000000
2,103.0,150.0,208.0,243.0,248.0,287.000000,317.000000,298.000000,289.000000,297.000000,258.000000,239.000000
3,110.0,123.0,99.0,109.0,103.0,134.000000,155.000000,157.000000,159.000000,195.000000,130.000000,158.000000
4,104.0,134.0,195.0,180.0,271.0,277.000000,316.000000,230.000000,201.000000,209.000000,153.000000,123.000000
5,153.0,147.0,156.0,164.0,190.0,253.000000,259.000000,290.000000,297.000000,294.000000,265.000000,250.000000
6,177.0,172.0,179.0,175.0,252.0,315.000000,242.000000,215.000000,258.000000,221.000000,196.000000,152.000000
7,115.0,92.0,103.0,108.0,134.0,129.000000,115.000000,99.000000,62.000000,56.000000,77.000000,61.000000
8,108.0,133.0,136.0,143.0,135.0,153.000000,140.000000,134.000000,194.000000,497.000000,262.000000,253.000000
9,111.0,127.0,152.0,164.0,176.0,248.000000,255.000000,240.000000,232.000000,347.000000,348.000000,396.000000
10,277.0,105.0,127.0,137.0,138.0,174.000000,181.000000,186.000000,213.000000,256.000000,260.000000,297.000000
11,15.0,29.0,34.0,42.0,65.0,76.000000,73.000000,71.000000,66.000000,74.000000,80.000000,46.000000
12,26.0,31.0,30.0,27.0,35.0,42.000000,48.000000,49.000000,46.000000,34.000000,47.000000,148.000000
13,123.0,200.0,177.0,179.0,193.0,227.000000,266.000000,201.000000,191.000000,261.000000,184.000000,512.000000
14,48.0,44.0,69.0,67.0,88.0,74.000000,92.000000,37.000000,45.000000,63.000000,78.000000,47.000000
15,27.0,63.0,49.0,54.0,55.0,92.000000,101.000000,115.000000,87.000000,76.000000,64.000000,77.000000
16,55.0,60.0,72.0,76.0,85.0,115.000000,123.000000,123.000000,148.000000,144.000000,153.000000,156.000000
17,122.0,167.0,165.0,130.0,164.0,161.000000,126.000000,156.000000,195.000000,223.000000,204.000000,232.000000
18,90.0,88.0,111.0,118.0,127.0,153.000000,133.000000,131.000000,141.000000,145.000000,120.000000,81.000000
19,80.0,76.0,96.0,118.0,122.0,153.000000,141.000000,179.000000,212.000000,216.000000,216.000000,180.000000
20,91.0,62.0,94.0,102.0,104.0,149.000000,110.000000,124.000000,131.000000,132.000000,233.000000,112.000000
21,118.0,196.0,130.0,138.0,160.0,181.000000,174.000000,156.000000,188.000000,96.000000,14.000000,55.000000
22,126.0,100.0,124.0,176.0,214.0,219.000000,221.000000,230.000000,285.000000,302.000000,296.000000,314.000000
23,249.0,252.0,302.0,416.0,324.0,411.000000,328.000000,263.000000,224.000000,299.000000,496.000000,382.000000
24,169.0,179.0,211.0,316.0,345.0,334.000000,317.000000,281.000000,286.000000,308.000000,265.000000,493.000000
25,166.0,145.0,190.0,255.0,256.0,154.000000,166.000000,157.000000,182.000000,204.000000,252.000000,177.000000
26,91.0,81.0,47.0,49.0,110.0,150.000000,149.000000,224.000000,304.000000,303.000000,265.000000,262.000000
27,208.0,214.0,203.0,243.0,265.0,332.000000,302.000000,305.000000,344.000000,271.000000,287.000000,340.000000
28,110.0,125.0,148.0,144.0,146.0,195.556722,183.948507,169.959094,166.800026,226.682266,214.304243,190.639921
29,177.0,303.0,200.0,158.0,177.0,152.000000,111.000000,144.000000,135.000000,126.000000,110.000000,292.000000
30,82.0,69.0,59.0,60.0,65.0,94.000000,71.000000,101.000000,108.000000,96.000000,91.000000,198.000000
31,289.0,328.0,325.0,380.0,146.0,257.000000,160.000000,130.636292,48.906181,298.315085,446.386677,398.615633
32,186.0,208.0,214.0,224.0,208.0,358.000000,233.000000,214.000000,219.000000,263.000000,250.000000,181.000000
33,90.0,94.0,103.0,113.0,129.0,140.000000,140.000000,131.000000,140.000000,146.000000,149.000000,142.000000

#Imputasi Mice

Menggunakan guide https://www.youtube.com/watch?v=W3A7WAeS31Y

Menggunakan guide miceforest https://pypi.org/project/miceforest/

In [28]:
!pip install miceforest
import miceforest as mf

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: miceforest in /usr/local/lib/python3.8/dist-packages (5.6.3)
Requirement already satisfied: lightgbm>=3.3.1 in /usr/local/lib/python3.8/dist-packages (from miceforest) (3.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from miceforest) (1.21.6)
Requirement already satisfied: blosc in /usr/local/lib/python3.8/dist-packages (from miceforest) (1.11.1)
Requirement already satisfied: dill in /usr/local/lib/python3.8/dist-packages (from miceforest) (0.3.6)
Requirement already satisfied: wheel in /usr/local/lib/python3.8/dist-packages (from lightgbm>=3.3.1->miceforest) (0.38.4)
Requirement already satisfied: scikit-learn!=0.22.0 in /usr/local/lib/python3.8/dist-packages (from lightgbm>=3.3.1->miceforest) (1.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from lightgbm>=3.3.1->miceforest) (1.7.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn!=0.22.0->lightgbm>=3.3.1->miceforest) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn!=0.22.0->lightgbm>=3.3.1->miceforest) (3.1.0)

In [43]:
kds = mf.ImputationKernel(df_nan, datasets=5, save_all_iterations=True,random_state=11)

kds.mice(9)

In [39]:
kds.complete_data(0)

,RPTTP100K 2021,RPTTP100K 2020,RPTTP100K 2019,RPTTP100K 2018,RPTTP100K 2017,RPTTP100K 2016,RPTTP100K 2015,RPTTP100K 2014,RPTTP100K 2013,RPTTP100K 2012,RPTTP100K 2011,RPTTP100K 2010
0,125.0,149.0,144.0,169.0,171.0,193.0,164.0,158.0,181.0,224.0,222.0,225.0
1,250.0,231.0,216.0,231.0,280.0,266.0,256.0,268.0,308.0,252.0,285.0,251.0
2,103.0,150.0,208.0,243.0,248.0,287.0,317.0,298.0,289.0,297.0,258.0,239.0
3,110.0,123.0,99.0,109.0,103.0,134.0,155.0,157.0,159.0,195.0,130.0,158.0
4,104.0,134.0,195.0,180.0,271.0,277.0,316.0,230.0,201.0,209.0,153.0,123.0
5,153.0,147.0,156.0,164.0,190.0,253.0,259.0,290.0,297.0,294.0,265.0,250.0
6,177.0,172.0,179.0,175.0,252.0,315.0,242.0,215.0,258.0,221.0,196.0,152.0
7,115.0,92.0,103.0,108.0,134.0,129.0,115.0,99.0,62.0,56.0,77.0,61.0
8,108.0,133.0,136.0,143.0,135.0,153.0,140.0,134.0,194.0,497.0,262.0,253.0
9,111.0,127.0,152.0,164.0,176.0,248.0,255.0,240.0,232.0,347.0,348.0,396.0
10,277.0,105.0,127.0,137.0,138.0,174.0,181.0,186.0,213.0,256.0,260.0,297.0
11,15.0,29.0,34.0,42.0,65.0,76.0,73.0,71.0,66.0,74.0,80.0,46.0
12,26.0,31.0,30.0,27.0,35.0,42.0,48.0,49.0,46.0,34.0,47.0,148.0
13,123.0,200.0,177.0,179.0,193.0,227.0,266.0,201.0,191.0,261.0,184.0,512.0
14,48.0,44.0,69.0,67.0,88.0,74.0,92.0,37.0,45.0,63.0,78.0,47.0
15,27.0,63.0,49.0,54.0,55.0,92.0,101.0,115.0,87.0,76.0,64.0,77.0
16,55.0,60.0,72.0,76.0,85.0,115.0,123.0,123.0,148.0,144.0,153.0,156.0
17,122.0,167.0,165.0,130.0,164.0,161.0,126.0,156.0,195.0,223.0,204.0,232.0
18,90.0,88.0,111.0,118.0,127.0,153.0,133.0,131.0,141.0,145.0,120.0,81.0
19,80.0,76.0,96.0,118.0,122.0,153.0,141.0,179.0,212.0,216.0,216.0,180.0
20,91.0,62.0,94.0,102.0,104.0,149.0,110.0,124.0,131.0,132.0,233.0,112.0
21,118.0,196.0,130.0,138.0,160.0,181.0,174.0,156.0,188.0,96.0,14.0,55.0
22,126.0,100.0,124.0,176.0,214.0,219.0,221.0,230.0,285.0,302.0,296.0,314.0
24,249.0,252.0,302.0,416.0,324.0,411.0,328.0,263.0,224.0,299.0,496.0,382.0
25,169.0,179.0,211.0,316.0,345.0,334.0,317.0,281.0,286.0,308.0,265.0,493.0
26,166.0,145.0,190.0,255.0,256.0,154.0,166.0,157.0,182.0,204.0,252.0,177.0
27,91.0,81.0,47.0,49.0,110.0,150.0,149.0,224.0,304.0,303.0,265.0,262.0
28,208.0,214.0,203.0,243.0,265.0,332.0,302.0,305.0,344.0,271.0,287.0,340.0
29,110.0,125.0,148.0,144.0,146.0,153.0,174.0,179.0,212.0,303.0,265.0,253.0
30,177.0,303.0,200.0,158.0,177.0,152.0,111.0,144.0,135.0,126.0,110.0,292.0
31,82.0,69.0,59.0,60.0,65.0,94.0,71.0,101.0,108.0,96.0,91.0,198.0
32,289.0,328.0,325.0,380.0,146.0,257.0,160.0,230.0,201.0,256.0,287.0,297.0
33,186.0,208.0,214.0,224.0,208.0,358.0,233.0,214.0,219.0,263.0,250.0,181.0
34,90.0,94.0,103.0,113.0,129.0,140.0,140.0,131.0,140.0,146.0,149.0,142.0

In [40]:
Finalresults = pd.concat([kds.complete_data(i) for i in range (5)]).groupby(level=0).mean()
Finalresults

,RPTTP100K 2021,RPTTP100K 2020,RPTTP100K 2019,RPTTP100K 2018,RPTTP100K 2017,RPTTP100K 2016,RPTTP100K 2015,RPTTP100K 2014,RPTTP100K 2013,RPTTP100K 2012,RPTTP100K 2011,RPTTP100K 2010
0,125.0,149.0,144.0,169.0,171.0,193.0,164.0,158.0,181.0,224.0,222.0,225.0
1,250.0,231.0,216.0,231.0,280.0,266.0,256.0,268.0,308.0,252.0,285.0,251.0
2,103.0,150.0,208.0,243.0,248.0,287.0,317.0,298.0,289.0,297.0,258.0,239.0
3,110.0,123.0,99.0,109.0,103.0,134.0,155.0,157.0,159.0,195.0,130.0,158.0
4,104.0,134.0,195.0,180.0,271.0,277.0,316.0,230.0,201.0,209.0,153.0,123.0
5,153.0,147.0,156.0,164.0,190.0,253.0,259.0,290.0,297.0,294.0,265.0,250.0
6,177.0,172.0,179.0,175.0,252.0,315.0,242.0,215.0,258.0,221.0,196.0,152.0
7,115.0,92.0,103.0,108.0,134.0,129.0,115.0,99.0,62.0,56.0,77.0,61.0
8,108.0,133.0,136.0,143.0,135.0,153.0,140.0,134.0,194.0,497.0,262.0,253.0
9,111.0,127.0,152.0,164.0,176.0,248.0,255.0,240.0,232.0,347.0,348.0,396.0
10,277.0,105.0,127.0,137.0,138.0,174.0,181.0,186.0,213.0,256.0,260.0,297.0
11,15.0,29.0,34.0,42.0,65.0,76.0,73.0,71.0,66.0,74.0,80.0,46.0
12,26.0,31.0,30.0,27.0,35.0,42.0,48.0,49.0,46.0,34.0,47.0,148.0
13,123.0,200.0,177.0,179.0,193.0,227.0,266.0,201.0,191.0,261.0,184.0,512.0
14,48.0,44.0,69.0,67.0,88.0,74.0,92.0,37.0,45.0,63.0,78.0,47.0
15,27.0,63.0,49.0,54.0,55.0,92.0,101.0,115.0,87.0,76.0,64.0,77.0
16,55.0,60.0,72.0,76.0,85.0,115.0,123.0,123.0,148.0,144.0,153.0,156.0
17,122.0,167.0,165.0,130.0,164.0,161.0,126.0,156.0,195.0,223.0,204.0,232.0
18,90.0,88.0,111.0,118.0,127.0,153.0,133.0,131.0,141.0,145.0,120.0,81.0
19,80.0,76.0,96.0,118.0,122.0,153.0,141.0,179.0,212.0,216.0,216.0,180.0
20,91.0,62.0,94.0,102.0,104.0,149.0,110.0,124.0,131.0,132.0,233.0,112.0
21,118.0,196.0,130.0,138.0,160.0,181.0,174.0,156.0,188.0,96.0,14.0,55.0
22,126.0,100.0,124.0,176.0,214.0,219.0,221.0,230.0,285.0,302.0,296.0,314.0
24,249.0,252.0,302.0,416.0,324.0,411.0,328.0,263.0,224.0,299.0,496.0,382.0
25,169.0,179.0,211.0,316.0,345.0,334.0,317.0,281.0,286.0,308.0,265.0,493.0
26,166.0,145.0,190.0,255.0,256.0,154.0,166.0,157.0,182.0,204.0,252.0,177.0
27,91.0,81.0,47.0,49.0,110.0,150.0,149.0,224.0,304.0,303.0,265.0,262.0
28,208.0,214.0,203.0,243.0,265.0,332.0,302.0,305.0,344.0,271.0,287.0,340.0
29,110.0,125.0,148.0,144.0,146.0,152.4,152.6,158.6,193.8,281.4,250.8,230.8
30,177.0,303.0,200.0,158.0,177.0,152.0,111.0,144.0,135.0,126.0,110.0,292.0
31,82.0,69.0,59.0,60.0,65.0,94.0,71.0,101.0,108.0,96.0,91.0,198.0
32,289.0,328.0,325.0,380.0,146.0,257.0,160.0,228.0,270.4,274.2,288.8,295.8
33,186.0,208.0,214.0,224.0,208.0,358.0,233.0,214.0,219.0,263.0,250.0,181.0
34,90.0,94.0,103.0,113.0,129.0,140.0,140.0,131.0,140.0,146.0,149.0,142.0

Data Null / Nan Telah Terisi isi